language: java
os: linux
dist: xenial
jdk:
  -openjdk8
env:
  matrix:
    - ANDROID_TARGET=android-29  ANDROID_ABI=armeabi-v7a
script:
  -bundle exec thor build
  
after_success:
  -bash <(curl -s https://codecov.io/bash)
