name: Custom Android CI with Gradle


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    link_checker:
      runs-on: ubuntu-latest
      steps:
        - uses: hashicorp/gh-action-check-broken-links@v1
          with:
            baseUrl: 'https://github.com/atharwa-24/VIT_Pune_Events'
            files: 'README.md'
    greeting&contri:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks!!!'' first issue'
          pr-message: 'Thanks! Each Contribution Counts'' first pr'
      - uses: akhilmhdh/contributors-readme-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Tests
        run: ./gradlew test

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

    label:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
